### PR TITLE
Guess The Number Game

### PR DESCRIPTION
**Pull request by ishan-nahid**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Issue

Fixes # [#77](https://github.com/Prodigy-InfoTech/Web-Development-Projects/issues/77).

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ishan-nahid** [comment]
Check, review and add hacktoberfest-accepted label

**Comment by prodigyinfotech** [comment]
Do not create duplicate PRs. 
As stated previously, do not add space before and after x in the PR template. 
ie. : `[x]` and not [ x ]

**Comment by ishan-nahid** [comment]
1. I Think now okay
2. i have added readme.md and added comment to js file. 

any need?

**Comment by ishan-nahid** [comment]
can you add the label now or i should do anything more?

**Pull request merged**
