### PR TITLE
Guestbook Web App

### LINKED ISSUE #49: Guestbook
Build a guestbook where visitors can leave comments, feedback, or testimonials on your website.

### PR DESCRIPTION
**Pull request by ankitsharma495**
# Description

Built a guestbook where visitors can leave comments, feedback on website, after clicking on submit button, the comments will be shown below the guestbook.

## Type of change
- [ ] Bug fix
- [x] New Project

## Issue
Fixes #49 

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Add issue number, fix markdown in PR template

**Comment by ankitsharma495** [comment]
sure sir. thanks for reviewing it

**Comment by ankitsharma495** [comment]
sir kindly review it. What else improvements i can do in it.

**Comment by prodigyinfotech** [comment]
Make sure the ticks are shown properly in the markdown of PR. 
Ie. remove the space before and after x in brackets

**Comment by prodigyinfotech** [comment]
Hey @ankitsharma495 please do the needful.
The markdown for tick should be: `[x]` and not `[ x ]` ie. no space should be present

**Comment by ankitsharma495** [comment]
i did the required changes sir. Thanks for your guidance.

**Pull request merged**
