### PR TITLE
text generator project added

### LINKED ISSUE #121: 🚀 Project: Text Generator
### 🔖 Project description

Text Generator is a versatile and user-friendly web application designed to generate dummy text quickly and efficiently. It provides users with the ability to input a desired number between 1 to 50 and receive a corresponding amount of sections containing dummy text. This project aims to streamline the process of generating placeholder text for various purposes such as web development, graphic design, content creation, and more.

### 🎤 Pitch

This project will help developers to have in-built tool for generating unlimited amount of dummy text. It will save time for them to not dodge upon different online tools instead of having their own tool for generating text for their projects.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Recdata**
# Description

Text Generator is a versatile and user-friendly web application designed to generate dummy text quickly and efficiently. It provides users with the ability to input a desired number between 1 to 50 and receive a corresponding amount of sections containing dummy text. This project aims to streamline the process of generating placeholder text for various purposes such as web development, graphic design, content creation, and more.

This project will help developers to have in-built tool for generating unlimited amount of dummy text. It will save time for them to not dodge upon different online tools instead of having their own tool for generating text for their projects.

## Issue

Fixes #121 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Create appropriate Project Issue

**Comment by Recdata** [comment]
Yes, added issue number link.

**Comment by prodigyinfotech** [comment]
Fill in the description PR

**Comment by Recdata** [comment]
Yes, description added

**Pull request merged**
