### PR TITLE
Resume Generator

### PR DESCRIPTION
**Pull request by yashwanthvarma18**
# Description

This pull request introduces a new project: the Resume Generator. This application allows users to create simple resumes quickly and efficiently. The motivation behind this project is to provide a simple and effective tool to generate resumes tailored to their needs. Relevant dependencies include `react`, `react-dom`, and `pdf-lib` for exporting resumes in PDF format.

## Issue

Fixes: #176

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:
- [x] I have included a README file for my project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

# Screenshots

Here are some screenshots of the Resume Generator:

1. **Home Screen:**
image
)

### CODE REVIEW

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech Thanks for giving me chance to contribute

**Comment by prodigyinfotech** [comment]
1. Remove unnecessary line brakes in PR template.  
2. Create a deployment of the project and add that in README file

**Comment by prodigyinfotech** [comment]
The templates selection in drop down only seems to change Font. So add support for different layouts 
Also, look into adding more fields

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech , as you mentioned to keep only the fields specified above, I have implemented them accordingly. You can merge my PR and open a new issue to enhance it, which will allow other contributors to take it as a challenge to solve. I also have several other PRs to submit
Hope you understand 
Thank You

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech  please merge it took so much time to make please merge it

**Comment by prodigyinfotech** [comment]
We have mentioned achievements already in our Issue.

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech Ok sure i will change

**Comment by yashwanthvarma18** [comment]
@prodigyinfotech 
Please review these changes and merge them 
image
image

**Comment by prodigyinfotech** [comment]
Looks good!

**Pull request merged**
