### PR TITLE
Contact app added

### PR DESCRIPTION
**Pull request by Ishaa11**
# Description

This app has a contact list , search contact functionality, delete , add , update contacts functionality and can go to a contact to get contact details
To start app:
cd contact-app
npm start
cd server-api
npm start (server will start at port 3006)

## Issue
Added a React Contact App where ypu can create a contact for a person, update it, delete that contact and search for a contact.
It uses a json server to store the contacts dynamically that acts as a dummy database.
Fixes # (issue)

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Hey @Ishaa11,

Create a new project issue under Issues

**Comment by Ishaa11** [comment]
# Description

This app has a contact list , search contact functionality, delete , add , update contacts functionality and can go to a contact to get contact details
To start app:
cd contact-app
npm start
cd server-api
npm start (server will start at port 3006)

## Issue
New Project : Contact App
Fixes # (issue)
added relative url in markdown

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

**Comment by prodigyinfotech** [comment]
Relative path is wrong. Fix it.
it should be something along: /contact-app/src/assets/ss.png

**Comment by Ishaa11** [comment]
fixed the urls

**Comment by prodigyinfotech** [comment]
Fixed the referencing issues. Now looks good to go.

**Pull request merged**
