### PR TITLE
Feature portfolio tracker

### LINKED ISSUE #47: Portfolio Tracker
Create a web app that allows users to track the performance of their stock or cryptocurrency investments.

### PR DESCRIPTION
**Pull request by NilanjanPramanik**
# Description
This PR add a feature Portfolio Tracker.  This app is made with React js .  Solves the isue #47 
## Home page
Screenshot 2023-10-10 180130

## Search Results
Screenshot 2023-10-10 180147

## Coin Page
Screenshot 2023-10-10 184910

## Issue

Fixes #47 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech Sir I have completed the task if there need some improvement please tell.

**Comment by prodigyinfotech** [comment]
Fix the folder name into something better.

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech  Sir, now is the file name appropriate ?

**Comment by prodigyinfotech** [comment]
Hey @NilanjanPramanik 
Rename the folder to: "Cryptocurrency Price Tracker"

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech sir, The folder is renamed

**Comment by prodigyinfotech** [comment]
Get rid of the unnecessary subfolder

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech Please check it sir.

**Comment by prodigyinfotech** [comment]
Looks much better,

**Comment by NilanjanPramanik** [comment]
@prodigyinfotech thank you so mach

**Pull request merged**
