### PR TITLE
added guessing game

### PR DESCRIPTION
**Pull request by ishan-nahid**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Issue

Fixes issue #77 

## Type of change
- [ ] Bug fix
- [ x ] New Project

# Checklist:

- [ x ] I have included a REAME file for my Project (not for Bug fix)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my code
- [ x ] I have commented my code, particularly in hard-to-understand areas 
- [ x ] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md) 

after
before

### CODE REVIEW

**Comment by ishan-nahid** [comment]
can you review and marge with hacktoberfest-accepted label ?

**Comment by ishan-nahid** [comment]
@TanvNaik @prodigyinfotech 
can you add hacktoberfest-accepted label to this?
otherwise it won't be countable for hacktoberfest.

**Comment by TanvNaik** [comment]
how do i add a label to pr?

**Comment by ishan-nahid** [comment]
label

for currency converter project, i have got accepted label, so why it is not possible for this? 
can you try again?

**Comment by prodigyinfotech** [comment]
Correct the PR Template, add missing README file
It will only be marked accepted if it follows our guidelines and is merged.

**Pull request closed without merging**
