### PR TITLE
Image Editing app that allows the user to edit their picture

### LINKED ISSUE #102: 🚀 Project:
### 🔖 Project description

Image Ditor is a simple image-editing web application built using HTML, CSS, and JavaScript. This application allows users to upload an image, make various edits to the image, and then download the edited image. Users can also reset the edits at any point during the editing process.

### 🎤 Pitch

Why It Should Be Added:
The Image Ditor project should be added to the open-source repository because it's a user-friendly image editing web app that serves practical needs. It encourages collaboration, offers learning opportunities, and benefits a diverse range of users in various domains.

How It Is Implemented:
The Image Ditor is implemented as a web application using HTML, CSS, and JavaScript. It allows users to upload images for editing, offers a range of editing features with parameter control, provides a reset option, and allows users to download their edited images. The project emphasizes a clear and intuitive user interface, making it accessible and easy to use.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by AshishGupta18**
# Description
Image Editor is a simple image-editing web application built using HTML, CSS, and JavaScript. This application allows users to upload an image, make various edits to the image, and then download the edited image. Users can also reset the edits at any point during the editing process.

## Issue
Fixes #102

## Type of change
- [x] New Project

# Checklist:

- [x] I have included a README file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by AshishGupta18** [comment]
@prodigyinfotech, please review and let me know if any changes are to be made.

**Comment by prodigyinfotech** [comment]
Please follow markdown syntax in your PR

**Comment by AshishGupta18** [comment]
@prodigyinfotech, done with the changes, let me know further if anything is missing

**Comment by prodigyinfotech** [comment]
Rename the folder to "Image Editor"

**Comment by AshishGupta18** [comment]
@prodigyinfotech, done with that too.

**Comment by prodigyinfotech** [comment]
The folder name should have space in between

**Comment by AshishGupta18** [comment]
@prodigyinfotech, done with that too

**Pull request merged**
