### PR TITLE
Added the code for Restaurant Menu Display

### PR DESCRIPTION
**Pull request by EshaalakshmiDS**
# Description

This web application is designed to help restaurants showcase their menu items with enticing images and detailed descriptions. It provides an engaging and informative experience for your customers, both in-house and online using Html, CSS, Js.
.

## Issue

Fixes: #136 

## Type of change
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech Please review the pull request and merge it. Thank you, This is my contribution to Hacktoberfest-2023

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech Please review the pull request and merge it. Thank you, This is my contribution to Hacktoberfest-2023

**Comment by prodigyinfotech** [comment]
Rename folder to "Restaurant Menu" only

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech I have created a new PR with updated folder name to "Restaurant Menu", Please review it and I request you to merge my PR, Thank you so much
#140 This is new PR.

**Pull request closed without merging**
