### PR TITLE
counter app

### LINKED ISSUE #43: 🚀 Project: Counter Application
### 🔖 Project description

If possible, I want to build a counter app that allows you to increase, decrease, and reset a counter value.

### 🎤 Pitch

I'll build it using HTML, CSS, and JavaScript.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by serhatbek**
# Description

Added a new counter application project using HTML, CSS and Javascript.

## Issue

Fixes #43

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
please fix the markdown in PR. Rest looks good.

**Comment by serhatbek** [comment]
Thank you for the feedback, I added the issue number. :)

**Comment by prodigyinfotech** [comment]
Hey @serhatbek please follow markdown syntax in the PR.
Also, The issue number should come immediately after the hashtag and not inside Parentheses.

**Comment by prodigyinfotech** [comment]
Hey @serhatbek I couldn't find any issue regarding this PR. Create a new Project issue and reference it in the PR.
Additionally. rename the folder into something better.

**Comment by serhatbek** [comment]
I did, thank you for your help.

**Pull request merged**
