### PR TITLE
Premium Plan webpage

### LINKED ISSUE #146: 🚀 Project: Premium Plan Webpage
### 🔖 Project description

This webpage is a premium plan containing webpage needed for some of the commercial websites.

### 🎤 Pitch

This project has the all kind of needs required to give a offer for premium plan to users of the commercial website.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by poudyalamit**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Issue

Fixes #146  (issue number)

## Type of change
- [x] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Create Appropriate issue

**Comment by poudyalamit** [comment]
Closes issue #146

**Comment by prodigyinfotech** [comment]
Drop 3D Models from commits, add some screenshot of the website

**Comment by poudyalamit** [comment]
@prodigyinfotech I have removed 3D Models.

**Comment by prodigyinfotech** [comment]
The current page only lists 1 premium package?
Please make it better but having 3-4 premium comparison

**Comment by poudyalamit** [comment]
It is about the template of premium plan for commercial purposes.

**Comment by prodigyinfotech** [comment]
Yes, but often websites have different plans that users can select. 
The current website is too basic for this topic to be considered

**Comment by poudyalamit** [comment]
@prodigyinfotech  I have added more plans which closes #142

**Pull request merged**
