### PR TITLE
currency converter is done

### LINKED ISSUE #7: Currency converter
This is a web application that converts one currency to another.

### PR DESCRIPTION
**Pull request by ishan-nahid**
# Description

I have written HTML, CSS and JS code for making currency converter. and uses frankfurter API for real time exchange rate.

## Issue
Fixes #7

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ishan-nahid** [comment]
review and marge.

**Comment by prodigyinfotech** [comment]
Hey @ishan-nahid, make sure to follow the complete checklist for the project to merge.

**Comment by ishan-nahid** [comment]
check now.

**Comment by ishan-nahid** [comment]
anything else?

**Comment by prodigyinfotech** [comment]
Looks good. Merged

**Pull request merged**
