### PR TITLE
Budget buddy

### LINKED ISSUE #144: 🚀 Project: Budget Buddy
### 🔖 Project description

A simple web app that helps users track their expenses, income, and budget. 

### 🎤 Pitch

Track your finances and stay on budget with our interactive expense tracker web app. Visualize your expenses with colorful charts and easily manage your income and spending.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by EshaalakshmiDS**
# Description

This web application helps you manage your finances and keep track of your expenses and income. It provides an easy-to-use interface for adding transactions, categorizing them, and visualizing your budget.

## Issue

Fixes #144  

## Type of change
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech Please review my PR that solves issue #144 . It is my contribution to Hacktoberfest-2023.

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech Please review my PR that solves issue #144  . It is my contribution to Hacktoberfest-2023.

**Comment by prodigyinfotech** [comment]
Remove .vscode folder, and some screenshots

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech yes ok. I will remove vscode folder and add some screenshots in the Readme file. Thank you so much

**Comment by EshaalakshmiDS** [comment]
@prodigyinfotech I have commited the necessary changes. Can u please review the PR now..Thank you

**Pull request merged**
